--- #YAML:1.0
name:               HTML-Tidy-libXML
version:            0.02
abstract:           Tidy HTML via XML::LibXML
author:
    - Dan Kogai <dankogai@dan.co.jp>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:   0
    XML::LibXML:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
